name: '@ngneat/cashew'

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Npm install
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: npm i

      - name: Test
        run: npm run test:lib

      - name: Build
        run: npm run build:lib

      - name: Build Playground
        run: npm run build
